language: node_js
# Once openjdk/oraclejdk dependencies are resolved, change to dist: xenial
dist: trusty
notifications:
  email: false
node_js: 10
matrix:
  fast_finish: true
env:
  - ES_VERSION=5.6.12
jdk:
  - oraclejdk8
install:
  - ./scripts/setup_ci.sh
  - npm i
script:
  - npm run travis
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - npm i -g npm
before_script:
  - sleep 10
  - curl http://127.0.0.1:9200/
  - node scripts/create_index.js -y
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: 10
      script: curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
      if: (branch = master) AND ( type = push )
